# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMX7mXjd1BtHifHJrifN1dWeSNWoE930
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

# --- 1. Model Parameters (Units: hours, meters, kcal, K) ---
F = 1.0           # m^3/h
V = 1.0           # m^3
Caf = 10.0        # kgmol/m^3
Tf = 298.0        # K
k0 = 36e6         # h^-1
E = 12000.0       # kcal/kgmol
R = 1.987         # kcal/kgmol K
dH = -6500.0      # kcal/kgmol
rho_Cp = 500.0    # kcal/m^3 K
UA = 150.0        # kcal/K h
Vj = 0.25         # m^3
Fj = 1.25         # m^3/h
Tj0 = 298.0       # K
rhoj_Cj = 600.0   # kcal/m^3 K

# --- 2. System Equations ---

def reaction_rate(Ca, T):
    # Arrhenius equation
    return k0 * np.exp(-E / (R * T)) * Ca

def system_odes(t, y):
    """
    Computes derivatives [dCa/dt, dT/dt, dTj/dt]
    y = [Ca, T, Tj]
    """
    Ca, T, Tj = y

    # Safety check to prevent overflow during unstable ignition
    if T > 2000: T = 2000

    r = reaction_rate(Ca, T)

    # Mass Balance: dCa/dt
    dCa_dt = (F/V)*(Caf - Ca) - r

    # Energy Balance Reactor: dT/dt
    dT_dt = (F/V)*(Tf - T) + ((-dH)/(rho_Cp))*r - (UA/(rho_Cp*V))*(T - Tj)

    # Energy Balance Jacket: dTj/dt
    dTj_dt = (Fj/Vj)*(Tj0 - Tj) + (UA/(rhoj_Cj*Vj))*(T - Tj)

    return np.array([dCa_dt, dT_dt, dTj_dt])

# --- 3. Runge-Kutta 4th Order Implementation ---

def rk4_step(func, t, y, h):
    """Calculates the next step using RK4 method."""
    k1 = func(t, y)
    k2 = func(t + 0.5*h, y + 0.5*h*k1)
    k3 = func(t + 0.5*h, y + 0.5*h*k2)
    k4 = func(t + h, y + h*k3)

    # Weighted average slope
    return y + (h/6.0)*(k1 + 2*k2 + 2*k3 + k4)

def solve_ode_rk4(y0, t_end, h=0.005):
    """
    Simulates the system from t=0 to t_end.
    h: step size in hours (small h prevents overflow)
    """
    t_values = np.arange(0, t_end, h)
    y_values = np.zeros((len(t_values), 3))

    y_curr = y0
    y_values[0] = y_curr

    for i in range(1, len(t_values)):
        t_curr = t_values[i-1]
        y_curr = rk4_step(system_odes, t_curr, y_curr, h)
        y_values[i] = y_curr

    return t_values, y_values

# --- 4. Find Steady States ---
def steady_state_func(x):
    return system_odes(0, x)

# Initial guesses tuned to find the 3 specific roots
guesses = [
    [8.0, 305, 300],  # Low T
    [6.0, 335, 305],  # Intermediate T
    [1.0, 390, 310]   # High T
]

steady_states = []
print(f"{'State':<15} {'Ca':<10} {'T (K)':<10} {'Tj (K)':<10}")
print("-" * 50)

for g in guesses:
    root = fsolve(steady_state_func, g)
    # Avoid duplicate roots
    if not any(np.allclose(root, s, atol=1.0) for s in steady_states):
        steady_states.append(root)

# Sort by Temperature for consistent labeling
steady_states.sort(key=lambda x: x[1])

labels = ["Low (Stable)", "Intermediate (Unstable)", "High (Stable)"]
for i, ss in enumerate(steady_states):
    print(f"{labels[i]:<15} {ss[0]:.4f}     {ss[1]:.2f}      {ss[2]:.2f}")

# --- 5. Simulation & Plotting ---
perturbations = [1, 5, 25] # Percentages
sim_time = 50 # hours

for i, ss in enumerate(steady_states):
    # Setup Figure
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    fig.suptitle(f"Dynamics from {labels[i]} Steady State (T_ss={ss[1]:.1f} K)", fontsize=14)

    var_names = ['$C_A$ (kgmol/m$^3$)', 'Reactor T (K)', 'Jacket $T_j$ (K)']

    for p in perturbations:
        # Perturb initial condition: y0 = SS + (p/100)*SS
        y0_pert = ss * (1 + p/100.0)

        # Run Simulation
        t_hist, y_hist = solve_ode_rk4(y0_pert, t_end=sim_time, h=0.005)

        # Plot
        axes[0].plot(t_hist, y_hist[:, 0], label=f'+{p}%')
        axes[1].plot(t_hist, y_hist[:, 1], label=f'+{p}%')
        axes[2].plot(t_hist, y_hist[:, 2], label=f'+{p}%')

    # Formatting
    for idx, ax in enumerate(axes):
        ax.set_title(var_names[idx])
        ax.axhline(ss[idx], color='k', linestyle='--', alpha=0.5, label='Steady State')
        ax.set_xlabel('Time (hours)')
        ax.set_ylabel(var_names[idx])
        ax.legend()
        ax.grid(True)

    plt.tight_layout()
    plt.show()